//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.30 at 03:01:51 PM AST 
//


package oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AcceptedVariantsDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AccountingCost;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ActivityType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AdditionalConditions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AdditionalInformation;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AgencyName;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AllowanceChargeReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ApprovalStatus;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AwardingCriterionDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.BackorderReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.BirthplaceName;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.BuildingNumber;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.BuyerReference;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CalculationExpression;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CancellationNote;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CandidateStatement;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CanonicalizationMethod;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CarrierServiceInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CertificateType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ChangeConditions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Channel;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Characteristics;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CodeValue;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Comment;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CompanyLegalForm;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Condition;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Conditions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ConditionsDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ConsumersEnergyLevel;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ConsumptionLevel;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ConsumptionType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Content;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ContractName;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ContractSubdivision;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ContractType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CorrectionType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CountrySubentity;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CurrentChargeType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CustomerReference;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CustomsClearanceServiceInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DamageRemarks;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DataSendingCapability;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DeliveryInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DemurrageInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Department;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Description;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.District;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DocumentDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DocumentHash;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DocumentStatusReasonDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.DocumentType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Duty;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ElectronicDeviceDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ElectronicMail;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ExclusionReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ExemptionReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Expression;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Extension;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.FeeDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Floor;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ForwarderServiceInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Frequency;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.FundingProgram;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.HandlingInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.HashAlgorithmMethod;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.HaulageInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.HeatingType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Information;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.InhouseMail;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.InstructionNote;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Instructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.InvoicingPartyReference;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.JobTitle;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Justification;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.JustificationDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Keyword;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.LatestMeterReadingMethod;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.LegalReference;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.LimitationDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Line;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ListValue;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Location;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Login;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.LossRisk;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.LowTendersDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MarkAttention;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MarkCare;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MaximumValue;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MeterConstant;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MeterName;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MeterNumber;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MeterReadingComments;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MeterReadingType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MinimumImprovementBid;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MinimumValue;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MonetaryScope;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.MovieTitle;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.NameSuffix;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.NegotiationDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Note;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.OneTimeChargeType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.OptionsDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.OrderableUnit;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.OrganizationDepartment;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.OtherInstruction;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.OutstandingReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PackingMaterial;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PartyType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Password;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PayPerView;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PayerReference;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PaymentDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PaymentNote;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PaymentOrderReference;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PersonalSituation;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PhoneNumber;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PlacardEndorsement;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PlacardNotation;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PlotIdentification;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PostalZone;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Postbox;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PreviousMeterReadingMethod;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PriceChangeReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PriceRevisionFormulaDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PriceType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PrintQualifier;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Priority;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PrizeDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ProcessDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ProcessReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Purpose;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Rank;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Reference;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Region;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.RegistrationNationality;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.RegulatoryDomain;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.RejectReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.RejectionNote;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Remarks;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ReplenishmentOwnerDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ResidenceType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Resolution;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.RoleDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Room;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SealingPartyType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ServiceNumberCalled;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ServiceType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ShippingMarks;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ShipsRequirements;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SignatureMethod;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SpecialInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SpecialServiceInstructions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SpecialTerms;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SpecialTransportRequirements;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.StatusReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SubscriberType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.SummaryDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TariffDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TaxExemptionReason;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TechnicalCommitteeDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TelecommunicationsServiceCall;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TelecommunicationsServiceCategory;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TelecommunicationsSupplyType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Telefax;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Telephone;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TestMethod;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Text;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TierRange;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TimeAmount;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TimezoneOffset;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TimingComplaint;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Title;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TradingRestrictions;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TransportServiceProviderRemarks;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TransportServiceProviderSpecialTerms;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TransportUserRemarks;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TransportUserSpecialTerms;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TransportationServiceDescription;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ValidateProcess;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ValidateTool;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ValidateToolVersion;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Value;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ValueQualifier;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.WarrantyInformation;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.Weight;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.WorkPhase;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.XPath;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionAgencyName;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionReason;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000019&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string (i.e. a finite set of characters), generally in the form of words of a language.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 * 
 * <p>Java class for TextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>TextType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType")
@XmlSeeAlso({
    TransportationServiceDescription.class,
    Floor.class,
    RegistrationNationality.class,
    Content.class,
    NameSuffix.class,
    DamageRemarks.class,
    HaulageInstructions.class,
    ForwarderServiceInstructions.class,
    Reference.class,
    Keyword.class,
    PackingMaterial.class,
    InhouseMail.class,
    Title.class,
    Duty.class,
    OtherInstruction.class,
    ListValue.class,
    BuildingNumber.class,
    PaymentOrderReference.class,
    SpecialInstructions.class,
    PlotIdentification.class,
    TimezoneOffset.class,
    CarrierServiceInstructions.class,
    RejectionNote.class,
    BirthplaceName.class,
    Department.class,
    SummaryDescription.class,
    RegulatoryDomain.class,
    BackorderReason.class,
    Information.class,
    Telephone.class,
    MeterConstant.class,
    MinimumImprovementBid.class,
    CorrectionType.class,
    Conditions.class,
    PostalZone.class,
    Expression.class,
    PaymentNote.class,
    CandidateStatement.class,
    DataSendingCapability.class,
    ContractName.class,
    ShippingMarks.class,
    Room.class,
    CodeValue.class,
    HandlingInstructions.class,
    Weight.class,
    TransportUserRemarks.class,
    OutstandingReason.class,
    Channel.class,
    Priority.class,
    Characteristics.class,
    TradingRestrictions.class,
    CustomsClearanceServiceInstructions.class,
    SpecialServiceInstructions.class,
    ApprovalStatus.class,
    Postbox.class,
    Purpose.class,
    DocumentType.class,
    PriceChangeReason.class,
    District.class,
    Region.class,
    CountrySubentity.class,
    TestMethod.class,
    RejectReason.class,
    CalculationExpression.class,
    CancellationNote.class,
    TimingComplaint.class,
    JobTitle.class,
    MarkAttention.class,
    MeterName.class,
    OrganizationDepartment.class,
    DocumentDescription.class,
    SpecialTransportRequirements.class,
    TransportServiceProviderRemarks.class,
    ElectronicMail.class,
    TaxExemptionReason.class,
    ContractType.class,
    Text.class,
    TariffDescription.class,
    LegalReference.class,
    AllowanceChargeReason.class,
    MarkCare.class,
    Telefax.class,
    DeliveryInstructions.class,
    StatusReason.class,
    AgencyName.class,
    PriceType.class,
    PayerReference.class,
    XPath.class,
    AwardingCriterionDescription.class,
    DemurrageInstructions.class,
    DocumentStatusReasonDescription.class,
    AdditionalInformation.class,
    InvoicingPartyReference.class,
    PrintQualifier.class,
    ExemptionReason.class,
    Extension.class,
    PlacardEndorsement.class,
    PlacardNotation.class,
    HashAlgorithmMethod.class,
    DocumentHash.class,
    ShipsRequirements.class,
    Location.class,
    Remarks.class,
    CertificateType.class,
    Instructions.class,
    ReplenishmentOwnerDescription.class,
    Resolution.class,
    ExclusionReason.class,
    ValueQualifier.class,
    TierRange.class,
    MeterReadingComments.class,
    LatestMeterReadingMethod.class,
    PreviousMeterReadingMethod.class,
    MeterReadingType.class,
    Comment.class,
    OptionsDescription.class,
    MonetaryScope.class,
    FeeDescription.class,
    ServiceType.class,
    PaymentDescription.class,
    PrizeDescription.class,
    LowTendersDescription.class,
    TechnicalCommitteeDescription.class,
    AdditionalConditions.class,
    FundingProgram.class,
    PriceRevisionFormulaDescription.class,
    AcceptedVariantsDescription.class,
    Login.class,
    Password.class,
    ActivityType.class,
    SealingPartyType.class,
    Condition.class,
    RoleDescription.class,
    PersonalSituation.class,
    CompanyLegalForm.class,
    Line.class,
    ElectronicDeviceDescription.class,
    ConditionsDescription.class,
    ProcessDescription.class,
    JustificationDescription.class,
    ProcessReason.class,
    NegotiationDescription.class,
    Rank.class,
    PartyType.class,
    PhoneNumber.class,
    TelecommunicationsSupplyType.class,
    HeatingType.class,
    ResidenceType.class,
    ConsumersEnergyLevel.class,
    TimeAmount.class,
    OneTimeChargeType.class,
    CurrentChargeType.class,
    ConsumptionType.class,
    SubscriberType.class,
    LimitationDescription.class,
    WarrantyInformation.class,
    OrderableUnit.class,
    ContractSubdivision.class,
    MaximumValue.class,
    MinimumValue.class,
    Value.class,
    ChangeConditions.class,
    TransportServiceProviderSpecialTerms.class,
    TransportUserSpecialTerms.class,
    ValidateToolVersion.class,
    ValidateTool.class,
    ValidateProcess.class,
    TelecommunicationsServiceCall.class,
    PayPerView.class,
    MovieTitle.class,
    TelecommunicationsServiceCategory.class,
    ServiceNumberCalled.class,
    Frequency.class,
    Justification.class,
    Description.class,
    ConsumptionLevel.class,
    MeterNumber.class,
    InstructionNote.class,
    LossRisk.class,
    SpecialTerms.class,
    SignatureMethod.class,
    CanonicalizationMethod.class,
    WorkPhase.class,
    CustomerReference.class,
    BuyerReference.class,
    AccountingCost.class,
    Note.class,
    ExtensionReason.class,
    ExtensionAgencyName.class
})
public class TextType
    extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.TextType
{


}
